#!/usr/bin/env bash

set -e

### consts #####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

## variables ###################################################################

registry_url="$1"
version=$(cat "$this_path/version")

### release ####################################################################

if [ -z "$registry_url" ]; then
  echo "Usage: $0 REGISTRY_URL"
  echo ""
  echo "  e.g.: $0 https://your.registry.com:5000/seleniumlibrary"
  exit 64
fi

echo "### Tagging image 'rfdocker:seleniumlibrary' to '$registry_url:$version'"
docker tag "rfdocker:seleniumlibrary" "$registry_url:$version"

echo "### Pushing image 'seleniumlibrary:$version' to registry..."
docker push "$registry_url:$version"

echo "### Tagging image 'rfdocker:seleniumlibrary' to '$registry_url:latest'"
docker tag "rfdocker:seleniumlibrary" "$registry_url:latest"

echo "### Pushing image 'rfdocker:seleniumlibrary' to '$registry_url:latest'"
docker push "$registry_url:latest"