#!/usr/bin/env bash

set -e
set -u

### main #######################################################################

echo -e "\n### Entering REPL"
docker run --rm -ti  \
  -e ZALENIUM_HOST=${ZALENIUM_HOST:-zalenium} \
  --link zalenium:zalenium \
  --entrypoint rfdebug \
  rf:latest "$@"
