#!/usr/bin/env bash

### consts #####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### settings ###################################################################

: ${ZALENIUM_NETWORK:="zalenium_default"}

### wrap rfdocker to run inside zalenium #######################################

ZALENIUM_NETWORK="$ZALENIUM_NETWORK" \
  "$this_path/zalenium" exec \
    RUN_ARGS="--network=$ZALENIUM_NETWORK" BUILD_DIR="$this_path/docker" \
      ./rfdocker -v GRID_HOST:zalenium ${@:-tests}
