#!/usr/bin/env bash

set -e

### globals ####################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### helpers ####################################################################

portable_timeout() {
  perl -e 'alarm shift; exec @ARGV' "$@";
}

wait_zalenium_started() {
  local done_msg="Zalenium is now ready!"
  while ! docker logs zalenium | grep "$done_msg" >/dev/null; do
    echo -n '.'
    sleep 0.2
  done
}
export -f wait_zalenium_started

### actions ####################################################################

up() {
  if ! docker top zalenium &>/dev/null ; then
    echo "### Pulling Docker image 'elgalu/selenium'"
    docker pull elgalu/selenium:3.5.3
    docker network create --driver bridge zalenium || true
    "$this_path/docker/build.sh"

    if [ "$(uname -s)" != 'Darwin' ]; then
      echo "### Setting non-Darwin specific flags"
      os_flags="-v $(which docker):/usr/bin/docker"
      os_flags="$os_flags -e HOST_GID=$UID"
      os_flags="$os_flags -e HOST_UID=$GID"
    fi

    echo "### Starting Zalenium in background"
    docker run -d -t --name zalenium -p 4444:4444 \
      $os_flags \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v "$this_path/videos":/home/seluser/videos \
      -e SAUCE_USERNAME="$SAUCE_USERNAME" \
      -e SAUCE_ACCESS_KEY="$SAUCE_ACCESS_KEY" \
      -e BROWSER_STACK_USER="$BROWSER_STACK_USER" \
      -e BROWSER_STACK_KEY="$BROWSER_STACK_KEY" \
      -e TESTINGBOT_KEY="$TESTINGBOT_KEY" \
      -e TESTINGBOT_SECRET="$TESTINGBOT_SECRET" \
      --network=zalenium \
      dosel/zalenium:3.5.3c start \
        --chromeContainers 1 \
        --firefoxContainers 0 \
        --maxDockerSeleniumContainers 4 \
        --screenWidth 1366 --screenHeight 768 \
        --timeZone "Europe/Helsinki" \
        --videoRecordingEnabled true \
        --sauceLabsEnabled false \
        --browserStackEnabled false \
        --testingBotEnabled false \
        --startTunnel false \
        --sendAnonymousUsageInfo false

    trap "docker stop zalenium ; docker rm zalenium ; exit 1" SIGINT SIGTERM ERR

    echo "### Waiting Zalenium to be started in background"
    if ! portable_timeout 60 bash -c wait_zalenium_started 2>/dev/null; then
      echo "Error: Zalenium starting timeouted, exiting."
      exit 124  # same as GNU coreutils `timeout` exit status
    fi

    echo "... ready for the tests"
  fi
}

down() {
  docker stop zalenium
  docker rm zalenium
  docker network remove zalenium
}

### main #######################################################################

action="$1"
[ -z "$action" ] && action="up"

case "$action" in
  up|start)
    up
    echo "### Zalenium running - to stop and remove: $0 down"
    ;;
  reload|restart)
    down || true
    up
    ;;
  down|destroy)
    down
    echo "### Done. Recorded videos were not removed."
    ;;
  exec)
    up
    shift
    eval "$@"
    ;;
  logs)
    docker logs zalenium --follow
    ;;
  *)
    echo "Usage: $0 (up|reload|down|logs)|(exec <command>)"
    exit 64
esac
