apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/videos
    type: DirectoryOrCreate
