apiVersion: v1
kind: Service
metadata:
  labels:
    app: zalenium
  name: zalenium
  namespace: default
spec:
  ports:
  - name: zalenium
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: zalenium
    role: grid
  type: NodePort
