{{- if eq true .Values.hub.persistentVolumesEnabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hub.fullname" . }}-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: efs-gp2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hub.fullname" . }}-videos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: efs-gp2
{{- end }}
