apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "fullname" . }}
    role: grid
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.hub.serviceAnnotations }}
  annotations:
{{ toYaml .Values.hub.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.hub.serviceType | quote }}
  sessionAffinity: {{ .Values.hub.serviceSessionAffinity | quote }}
  ports:
  - name: hub
    port: {{ .Values.hub.port }}
    targetPort: {{ .Values.hub.port }}
  selector:
    app: {{ template "hub.fullname" . }}
    role: grid
